version: "3"

services:
    app:
        image: erasmo/projeto_os
        ports:
            - "8000:8000"
        volumes:
            - ~/GITHUB/projeto_OS/:/app
        depends_on:
            - db

    db:
        image: mysql:latest
        container_name: erasmo_dados
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: p@ssword
        ports:
         - "3300:3300"

volumes:
    mysql-data:
